WebApplication8/Models/ForumMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication8.Models
{
    public class ForumMessage
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid ForumTopicId { get; set; }
        [Required]
        public String ApplicationUserId { get; set; }

        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        [Required]
        public String Text { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
        public ForumTopic ForumTopic { get; set; }
        public ICollection<ForumMessageAttachment> ForumMessageAttachments { get; set; }
    }
}

WebApplication8/Controllers/ForumMessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication8.Data;
using WebApplication8.Models;
using WebApplication8.Models.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace WebApplication8.Controllers
{
    public class ForumMessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ForumMessagesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

   
        public async Task<IActionResult> Index(Guid? TopicId)
        {
            if (TopicId == null)
            {
                return this.NotFound();
            }

            var topic = await this._context.ForumTopics
                .SingleOrDefaultAsync(x => x.Id == TopicId);

            if (topic == null)
            {
                return this.NotFound();
            }

            this.ViewBag.Topic = topic;
            var messages = await this._context.ForumMessages
                .Include(x=> x.ForumMessageAttachments)
                .Where(x => x.ForumTopicId == TopicId)
                .ToListAsync();

            return this.View(messages);
        }


    
        public async Task<IActionResult> Create(Guid? TopicId)
        {
            if (TopicId == null)
            {
                return this.NotFound();
            }

            var topic = await this._context.ForumTopics
                .SingleOrDefaultAsync(x => x.Id == TopicId);

            if (topic == null)
            {
                return this.NotFound();
            }

            this.ViewBag.Topic = topic;
            return this.View(new ForumMessageCreateModel());
        }


     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid? TopicId, ForumMessageCreateModel model)
        {
            if (TopicId == null)
            {
                return this.NotFound();
            }

            var topic = await this._context.ForumTopics
                .SingleOrDefaultAsync(x => x.Id == TopicId);

            if (topic == null)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                var message = new ForumMessage
                {
                    Text = model.Text,
                    Created = DateTime.Now,
                    Modified = DateTime.Now,
                    ApplicationUserId = _userManager.GetUserId(User),
                    ForumTopicId = (Guid)TopicId

                };

                this._context.Add(message);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Index", new { topicId = topic.Id });
            }

            this.ViewBag.Topic = topic;
            return this.View(model);
        }


  
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages.SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", forumMessage.ApplicationUserId);
            ViewData["ForumTopicId"] = new SelectList(_context.ForumTopics, "Id", "ApplicationUserId", forumMessage.ForumTopicId);
            return View(forumMessage);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ForumTopicId,ApplicationUserId,Created,Modified,Text")] ForumMessage forumMessage)
        {
            if (id != forumMessage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forumMessage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumMessageExists(forumMessage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", forumMessage.ApplicationUserId);
            ViewData["ForumTopicId"] = new SelectList(_context.ForumTopics, "Id", "ApplicationUserId", forumMessage.ForumTopicId);
            return View(forumMessage);
        }

  
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forumMessage = await _context.ForumMessages
                .Include(f => f.ApplicationUser)
                .Include(f => f.ForumTopic)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (forumMessage == null)
            {
                return NotFound();
            }

            return View(forumMessage);
        }

    
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var forumMessage = await _context.ForumMessages.SingleOrDefaultAsync(m => m.Id == id);
            _context.ForumMessages.Remove(forumMessage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumMessageExists(Guid id)
        {
            return _context.ForumMessages.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Back(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var topic = await this._context.ForumTopics
               .SingleOrDefaultAsync(x => x.Id == id);

            return this.RedirectToAction("Index", "ForumTopics" ,new { topic.ForumId });
        }

    }
}

WebApplication8/Views/ForumMessages/Create.cshtml
@model WebApplication8.Models.ViewModels.ForumMessageCreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ForumMessage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-topicId="@ViewBag.Topic.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication8/Views/ForumMessages/Delete.cshtml
@model WebApplication8.Models.ForumMessage

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ForumMessage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ForumTopic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ForumTopic.ApplicationUserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication8/Views/ForumMessages/Details.cshtml
@model WebApplication8.Models.ForumMessage

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ForumMessage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ForumTopic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ForumTopic.ApplicationUserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication8/Views/ForumMessages/Edit.cshtml
@model WebApplication8.Models.ForumMessage

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ForumMessage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ForumTopicId" class="control-label"></label>
                <select asp-for="ForumTopicId" class="form-control" asp-items="ViewBag.ForumTopicId"></select>
                <span asp-validation-for="ForumTopicId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication8/Views/ForumMessages/Index.cshtml
@model IEnumerable<WebApplication8.Models.ForumMessage>

<h2>First topic</h2>

@if (User.Identity.IsAuthenticated)
{
    <p>
        <a asp-action="Create" asp-controller="ForumMessages" asp-route-topicId="@ViewBag.Topic.Id">Reply</a>
        @*| <a asp-action="Edit" asp-controller="ForumMessages" asp-route-topicId="@ViewBag.Topic.Id">Edit</a>*@
        @*| <a asp-action="Delete" asp-controller="ForumMessages" asp-route-topicId="@ViewBag.Topic.Id">Delete</a>*@
        | <a asp-action="Back" asp-controller="ForumMessages" asp-route-id="@ViewBag.Topic.Id">Back to Forum 1</a>
    </p>
}
    @foreach (var message in Model)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <div>
                    By person in @message.Created
                    | <a href="#">Edit</a>
                    | <a href="#">Delete</a>
                    | <a asp-action="Create" asp-controller="ForumMessageAttachments" asp-route-Id="@message.Id">Attach</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="forum-message-text">
                    @message.Text
                </div>
                <div class="row">
                        @foreach (var Item in message.ForumMessageAttachments)
                        {
                            <div class="col-sm-6 col-md-4">
                                <div class="thumbnail">
                                    <a href="@Item.FilePath" target="__blank">
                                        <img src="@Item.FilePath" alt="Attachment" />
                                    </a>
                                </div>
                                <div class="caption">
                                    <p><a asp-controller="ForumAttachmentsController" asp-action="Delete" asp-route-id="Item.Id" class="btn btn-sm btn-danger">Delete</a></p>
                                </div>
                            </div>
                        }
                </div>
            </div>
        </div>
    }